jdk:
  - openjdk21
before_install:
  - sdk install java 21.0.2-open
  - sdk use java 21.0.2-open
install:
  - ./gradlew :spice-core:publishToMavenLocal :spice-agents:publishToMavenLocal :spice-springboot:publishToMavenLocal :spice-springboot-ai:publishToMavenLocal :spice-springboot-statemachine:publishToMavenLocal :spice-infra:publishToMavenLocal -x test